### ISSUE TITLE
Include a infix for Option.default

### ISSUE THREAD

**Issue by grsabreu** [Risto-Stevcev/bs-abstract#1]
Would be nice to have an infix for https://github.com/Risto-Stevcev/bs-abstract/blob/master/src/implementations/Option.re#L6

Maybe `|?`, if you accept the idea I can go ahead and make a PR for it

**Comment by Risto-Stevcev** [comment]
Added on 10f2434ddc478ea495d7711f8c751c33267f24f7

**Comment by grsabreu** [comment]
Sorry, I just saw the reply now. That's awesome!
