### ISSUE TITLE
Unfoldable

### ISSUE THREAD

**Issue by esbullington** [Risto-Stevcev/bs-abstract#15]
I noticed `Unfoldable` was mentioned alongside a few other interfaces in an issue about a year ago, and then the issue was closed without comment in March. Are you open to an `Unfoldable` PR, or did you decide against?

Having an `unfold` would be handy.

**Comment by Risto-Stevcev** [comment]
I didn't close that ticket, maybe @texastoland just didn't have the time to work on it. Yeah I'm open for it

**Comment by Risto-Stevcev** [comment]
Resolved with https://github.com/Risto-Stevcev/bs-abstract/pull/16
